### ISSUE TITLE
Failed to create default route from app name

### ISSUE THREAD

**Issue by armbrustsamuel** [SAP-samples/sap-tech-bytes#11]
Hi colleagues,

I am testing the deployment of 2 Minutes of SAPUI5 - 7 (Authorization) in the hanatrial account (locally, it works fine), using:

```bash
cf push mta_archives/ui5-approuter_1.0.0.mtar
```

So, I am facing the following error:

```bash
Failed to create default route from app name: Host must be either "*" or contain only alphanumeric characters, "_", or "-"
```

I tried to adjust the mtar.yaml, adding a route without success. Also, I tried to create a route manually in the BTP cockpit, but it also didn't work. In the cf logs, it says that the default route is true, so it stops deploying.

Do you have some suggestion about this issue? Maybe it can be a limitation of hanatrial account, but I am not sure about that.

**Comment by nicogeburek** [comment]
Hi there, with `.mtar` files you want to use `cf deploy` instead of `cf push` (which is for when you use a `manifest.yaml`). In case you don't have the MTA plugin for the Cloud Foundry CLI that gives you the `cf deploy` command check [this](https://developers.sap.com/tutorials/cp-cf-install-cliplugin-mta.html?source=social-Global-YOUTUBE-MarketingCampaign-Developers-unspecified-spr-6346404967-account_name&campaigncode=CRM-XB22-MKT-DGEALL&sprinklrid=6346404967) out.
